POST http://localhost:3003/api/chatRooms/650ae0898f205d3bd3719bdf/messages
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvLm0iLCJpZCI6IjY1MGFlMDQwOGYyMDVkM2JkMzcxOWJkMyIsImlhdCI6MTY5NTIxMTU5N30.sC5p91It6Icc7csNb-LLSa55sS2HSHOe2Wj1UNx2-UE

{
  "from": "650ae0408f205d3bd3719bd3",
  "to": "650ae0698f205d3bd3719bd8",
  "text": "Hello world"
}