GET http://localhost:3003/api/users
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvLm0iLCJpZCI6IjY1MGFlMDQwOGYyMDVkM2JkMzcxOWJkMyIsImlhdCI6MTY5NTIxMTU5N30.sC5p91It6Icc7csNb-LLSa55sS2HSHOe2Wj1UNx2-UE