GET http://localhost:3003/api/chatRooms/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYmxvLm0iLCJpZCI6IjY1MDVkMTU1NTA0NjEyOTJlYTk2MzBiNSIsImlhdCI6MTY5NTAyNjY5MX0.3tmYrQ7bSFMlM4p4qW7YTAbn0qo5-HbKZJAO15blOuk